[package]
name = "git-playground"
version = "0.1.0"
edition = "2024"

[dependencies]
git2 = "0.20.1"

[dev-dependencies]
tempfile = "3.19.1"
once_cell = "1.21.3"
serial_test = "3.2.0"
uuid = { version = "1.16.0", features = ["v4"] }
